version: '3.9'

services:
  n8n:
    image: n8nio/n8n:1.103.2
    restart: always
    environment:
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_DATABASE: evolutionapi_db
      DB_POSTGRESDB_USER: evolutionuser
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./n8n_data:/home/node/.n8n
    depends_on:
      - postgres

  evolution_api:
    image: atendai/evolution-api:v2.1.1
    restart: always
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: evolutionapi_db
      DATABASE_USER: evolutionuser
      DATABASE_PASS: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: evolutionapi_db
      POSTGRES_USER: evolutionuser
      POSTGRES_PASSWORD: P0stgr3s_S3cur3_P@ssw0rd!
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always

volumes:
  n8n_data:
  evolution_store:
  evolution_instances:
  postgres_data:
  redis_data:

networks:
  whatsapp-net:
    driver: bridge